[package]
name = "fstore"
version = "0.1.0"
edition = "2021"
authors = ["Ranjeeth Mahankali <ranjeethmahankali@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4", features = ["cargo"] }
hashbrown = "0.14"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
glob-match = "0.2"
edit = "0.1"
